### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/alholmbe-sorting#1]
**Well done Alexander!**

Not only did you write psudocode, you must have forgot to push your visualisation of merge sort and the sorting algorithm of your choice.

Lets comprimise; I'll give you _Pass_ if you simply submit an implementation of the missing sorting algorithms, but not necessary the visualisation logic for them. This could be as easy as submitting the code in markdown as an issue comment.

#### Notes on your code:

Since psudocode allows for summarized writing, I feel like being petty. Your implementation of selection sort has a tiny tiny puny lack of consistency.

_Your code_:
```py
current_min_index = i
current_min_value = lst[i]
for j in range((i + 1), len(lst)):
    if lst[j] < current_min_value:
        current_min_index = j
        current_min_value = lst[j]

tmp = lst[i]
lst[i] = lst[current_min_index]
```
_Option 1 (rid of the excessive indexation)_:
```py
current_min_index = i
current_min_value = lst[i]
# ...
lst[i] = current_min_value
```
_Option 2 (since collection indexation is a constant operation)_:
```py
current_min_index = i
for j in range((i + 1), len(lst)):
    if lst[j] < lst[current_min_index]:
        current_min_index = j

#...
```

**Comment by holma91** [comment]
hmm weird, the visualizations should work with pygame installed. However, I pushed two new files now with mergesort and an algorithm of my choice, bubblesort.

**Comment by violaso** [comment]
Thanks!
